### ISSUE TITLE
states-of-matter-basics fails build

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter-basics#13]
```
% cd states-of-matter-basics
% grunt
Running "jshint:allFiles" (jshint) task
>> 461 files lint free.

Running "clean" task

Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT: no such file or directory, open '/Users/cmalley/PhET/GitHub/states-of-matter/js/solid-liquid-gas/SolidLiquidGasScreen.js'
>> In module tree:
>>     states-of-matter-basics-main
>> 
>>     at Error (native)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
```

I have master of all repositories check out. This `require` call is failing in states-of-matter-basics-main.js:

```js
var SolidLiquidGasScreen = require( 'STATES_OF_MATTER/solid-liquid-gas/SolidLiquidGasScreen' );
```

There is no directory named 'solid-liquid-gas' in the states-of-matter repository. And I don't see SolidLiquidGasScreen.js in any of the repositories listed in chipper/data/active-repos. 

Did you forget to push something to GitHub? 
Or relocate something without updating the path here?

**Comment by pixelzoom** [comment]
Reassigning to @jbphet, he broke this in https://github.com/phetsims/states-of-matter/commit/2bdc8a110d71710fece4e8f85bfde2325b5e2550.

**Comment by pixelzoom** [comment]
Fixed in above commit. @jbphet please verify.

**Comment by jbphet** [comment]
Looks good, thanks.  Closing.
