### ISSUE TITLE
User question: molecule behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter-basics#14]
> Recently I was doing a worksheet in science class  at Prairie Star Middle School in Leawood, Kansas using your States of Matter: Basic simulator and I noticed when the water molecules are heated to the point where the cap explodes off the can and then cooled to zero Kelvin, the few remaining molecules are still moving despite being at zero Kelvin when they shouldn't be able to move due to the lack of energy. I was just wondering why this is and was hoping you could explain it.

**Comment by jbphet** [comment]
@oliver-phet - please respond with something like the following:

> This is a very interesting test - one that we apparently didn't run - and the sim doesn't handle the situation correctly.  Thanks for bringing this to our attention.  The reason that this behavior occurs is that the software that underlies the simulation doesn't pay attention to any heating or cooling for the particles once the lid blows off, since most of the particles are then outside of the container.  The problem is that the thermometer DOES still pay attention to the heating and cooling, which it shouldn't.

> We are about to release a new HTML5 version of this simulation that will run in most browsers without requiring Java.  In this version, the thermometer is attached to the lid, and flies off with the lid when the extreme pressure threshold is reached, so the problem that you have described won't occur.

> Again, thanks for letting us know about this, and thanks for using PhET simulations.

**Comment by oliver-phet** [comment]
Response to user sent. Closing.
