### ISSUE TITLE
"Solid" drifts to the left on States Screen

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter-basics#15]
Start the sim and open the States screen. The atoms gradually shift to the left. This behavior isn't in the full version. 

<img width="1440" alt="screen shot 2016-12-22 at 2 59 12 pm" src="https://cloud.githubusercontent.com/assets/5090275/21441822/5fb3a6de-c857-11e6-8868-399cdf2aacb4.png">

Looks like it occurs on Phase Changes as well.

**Comment by oliver-phet** [comment]
Whoops - I take it back. The full version does this too. Intentional?

**Comment by oliver-phet** [comment]
Looks like this was present in Java too: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2057

**Comment by jbphet** [comment]
I did two things to fix this:
+ added a step to the code the forms the solid that averages the velocity to zero
+ added a slight concavity to the bottom of the container to push the particles back towards the center if they drift

The latter was done as part of a larger commit to address drift, see https://github.com/phetsims/states-of-matter/commit/4a526e2838ff0634c1580d723b0396eecaf0ca06.

So far, this seems to be working pretty well.

**Comment by jbphet** [comment]
I'm going to have to back out the concave bottom.  During testing I found that this can cause side-to-side oscillations of the solid when it gets to absolute zero.

**Comment by KatieWoe** [comment]
Looks good.  Closing

**Comment by KatieWoe** [comment]
This also looks good in 1.1.0-rc.2 Of basics
