### ISSUE TITLE
User reported issue: particles scatter outside of container

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/states-of-matter-basics#16]
Report a Problem
Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device: Windows Pc

Operating System:  Windows 7

Browser: chrome

Problem description: on solids liquids gases  on both simple page and phases stage at some point during the solid->liquid state the particles scatter across the screen – outside the container… sometimes coming back in

Steps to reproduce:
Somewhere in solid->liquid phase heating?

Severity: severe –
Cant use sim for lesson

Screenshots:
![image](https://user-images.githubusercontent.com/5090275/35289780-9019f38a-0025-11e8-9b83-181db5cf6c0b.png)

Troubleshooting information (do not edit):
Name: ‪States of Matter: Basics

URL: https://phet.colorado.edu/sims/html/states-of-matter-basics/latest/states-of-matter-basics_en.html

Version: 1.0.2 2017-04-16 15:58:41 UTC

Features missing: touch

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

Language: en-US

Window: 1280x588

Pixel Ratio: 1/1

WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)

GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)

Vendor: WebKit (WebKit WebGL)

Vertex: attribs: 16 varying: 20 uniform: 253

Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 8192x8192

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"1ea1df65","branch":"HEAD"},"axon":{"sha":"1fba32ce","branch":"HEAD"},"babel":{"sha":"b92a2966","branch":"master"},"brand":{"sha":"2c7dc287","branch":"HEAD"},"chipper":{"sha":"c18236bf","branch":"HEAD"},"dot":{"sha":"a014950f","branch":"HEAD"},"joist":{"sha":"4941f5c9","branch":"HEAD"},"kite":{"sha":"e5affc4c","branch":"HEAD"},"nitroglycerin":{"sha":"bb4cf015","branch":"HEAD"},"phet-core":{"sha":"87b5cab3","branch":"HEAD"},"phetcommon":{"sha":"4c738814","branch":"HEAD"},"query-string-machine":{"sha":"b38c3c25","branch":"HEAD"},"scenery":{"sha":"cd3a7a2d","branch":"HEAD"},"scenery-phet":{"sha":"fdf8f08e","branch":"HEAD"},"sherpa":{"sha":"727a3136","branch":"HEAD"},"states-of-matter":{"sha":"f9b05a78","branch":"HEAD"},"states-of-matter-basics":{"sha":"4c3a4719","branch":"HEAD"},"sun":{"sha":"e86f9f50","branch":"HEAD"},"tandem":{"sha":"b83eb2e2","branch":"HEAD"}}

**Comment by jbphet** [comment]
@phet-steele - Can you work with the QA team to see if anyone can duplicate this?  If I'm reading the user agent info correctly, this user was on Windows 7 and a pretty recent version of Chrome.  I just messed around on Win 10 + Chrome for several minutes and wasn't able to get anything like this to happen.

**Comment by phet-steele** [comment]
@jbphet I don't think this suite of sims ever got https://github.com/phetsims/joist/commit/d48e6da62a0c9c7a9edecba36069a45d4d71d47b#diff-1a1c3747494feba507339d0cc74ad5ca. I can reproduce the above by setting my system clock back in time. The user's computer must be doing something fun with dt to be doing this "naturally".

**Comment by jbphet** [comment]
I've updated the master branch to use the latest joist support for limiting time stamps.  I'll mark this as fixed an leave open for verification on upcoming RC.

**Comment by KatieWoe** [comment]
Looks good on Mac.  Closing.
