### ISSUE TITLE
Slight pointer area overlap

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#21]
For https://github.com/phetsims/QA/issues/297
When the sim is paused the pause/unpause button is a bit bigger, meaning that the pointer area for the button overlaps just a bit with the step forward button.  Sorry this wasn't caught earlier.  Likely minor due to the very small amount of overlap.
![overlappointspause](https://user-images.githubusercontent.com/41024075/54945877-7600cd80-4efc-11e9-848c-858665f3c056.gif)

**Comment by jbphet** [comment]
I reduced the touch area dilation, it now looks like this:

![image](https://user-images.githubusercontent.com/3082831/55515549-17d49880-5628-11e9-97a9-391375d20fcf.png)

**Comment by jbphet** [comment]
This was a minor fix, easily verified, so I did it and went ahead and deployed the production version.  Closing.
