### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter-basics#22]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Switching between Kelvin and Celsius could be difficult

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56228041-1184ea00-6034-11e9-9066-312919a40481.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56228042-1184ea00-6034-11e9-819b-1187dc852663.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56228043-121d8080-6034-11e9-8209-fe6ad0dc6b95.png)

**Comment by KatieWoe** [comment]
Also, should the pump have touchSnag?

**Comment by arouinfar** [comment]
Thanks @KatieWoe.

Since the SOMB code lives in `states-of-matter`, we can address these concerns in https://github.com/phetsims/states-of-matter/issues/243, so I'll go ahead and close this issue.
