### ISSUE TITLE
Fix up the client guide for 1.2.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter-basics#30]
There are a number of updates that are being made to the client guide for states-of-matter, and many of those updates will need to be made to states-of-matter-basics too.  This issue is to make sure that it happens before the next RC.

@arouinfar - assigning to you for now, please assign back to me when this is ready for inclusion in an RC.  It has been requested that I get the next RC out by around 1pm tomorrow, 8/14/2020, so I'll need it by then.

**Comment by arouinfar** [comment]
@jbphet the SOMB guide has been updated in the above commits. I originally referenced the in the parent SOM issues.

**Comment by jbphet** [comment]
Thanks @arouinfar.  This should be checked as part of the 1.2 release test process.

**Comment by jbphet** [comment]
@arouinfar - I think this should be done, and the revised version has been published.  Can you please check the client guide and make sure everything is as it should be and, if so, close this issue?

**Comment by arouinfar** [comment]
Looks good in the 1.2.0 version @jbphet.
