### ISSUE TITLE
Deploy from the 1.2 branch

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter-basics#31]
Version 1.2.0 of states-of-matter (SOM) - the "parent sim" of states-of-matter-basics (SOMB) - was just deployed.  The main purpose of this release was to add phet-io functionality, but there were also a number of bug fixes and other changes.  SOMB 1.2.0 should be deployed using the same code as SOM so that it also picks up the phet-io functionality and bug fixes.

**Comment by ariel-phet** [comment]
Marking as medium priority, as I agree this task would be good to complete sooner than later. Lets try to get into QA pipeline by mid November (sooner being ideal). Sounds like @jbphet might have some time this Friday.

**Comment by jbphet** [comment]
@arouinfar, @kathy-phet, and I discussed whether or not to include the phet-io brand with this release, and we agreed that we _should_ include it.  Here's the Slack dialog:

> @jbphet 10:40 AM
K**** and A**** - I have "States of Matter: Basics" all set for an RC using the code that was used for the recent "States of Matter" release.  I have been assuming that I should publish both the PhET and PhET-iO brands, but it occurred to me that I should probably check in with you on this.  Shall I move forward with both brands? (edited) 
>
> @arouinfar 10:47 AM
I think we should probably include both brands, especially since the client  originally wanted to use the basics version.
>
> @jbphet 11:01 AM
Sounds reasonable.  Will it require any changes to the client guide?
>
> @arouinfar 11:02 AM
It shouldn’t. I created SOMB-specific guides at the same times as the ones for SOM, and any tweaks that were made to SOM guides during QA were also applied to SOMB.
>
> @jbphet 11:04 AM
Sounds good.
Next question: I'm assuming that I should NOT publish the phet-io version of Atomic Interactions, and just publish the phet brand.  Sound good?
>
> @arouinfar 11:04 AM
That sounds good to me. There was never any phet-io design review of Atomic Interactions.
>
> @kathy-phet 11:05 AM
Both decisions sound good. When we have a request for Atomic Interactions PhET-iO, we can prioritize finishing that up.

**Comment by jbphet** [comment]
Here's the QA task for the first serious release on this branch: https://github.com/phetsims/QA/issues/574.  This is for rc.3, and the reason that it's not 1 is because initially I was trying to put the 1.2 release of this sim out at the same time as the primary SOM release, but that plan was aborted due to limited bandwidth in QA.

**Comment by jbphet** [comment]
Deployment complete, closing.
