### ISSUE TITLE
Performance Lag when Maximizing Window

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter-basics#4]
There is a noticeable lag in performance when the window is maximized on my MacBook running the latest Chrome.  Since my external monitor is significantly larger than iPad resolution, I'm not sure if this is something we should prioritize. Assigning to @ariel-phet for input.

Here's a video clip of the behavior:
https://drive.google.com/file/d/0B-YvjkIIcS_aUzVNMDAtNm9GcEU/view?usp=sharing

**Comment by ariel-phet** [comment]
My guess is we are going to have to do some performance optimization on this sim. I believe @jbphet has mentioned that we might need to try webgl for the particles (which might solve this issue).

**Comment by jbphet** [comment]
@arouinfar - please test on https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-rc.1/phet/states-of-matter_en_phet.html and see if this is still a problem.

**Comment by KatieWoe** [comment]
@jbphet looks ok on 10.14 chrome.  Both maximized window and full screen.  I don't have an external monitor hookup for the Mac, but just on the laptop it looks fine.

**Comment by jbphet** [comment]
Thanks for taking a look.  I think it's safe to close at this point.
