### ISSUE TITLE
Credits are missing

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter-basics#5]
Credits need to be added for this sim.

**Comment by jbphet** [comment]
Initial credits have been added, will leave this open for now to remind us to finalize them before starting the release process.

**Comment by jbphet** [comment]
Assigning to @ariel-phet to check over the credits and recommend any updates or close.

**Comment by ariel-phet** [comment]
my name should be "Ariel" not "Arial" but otherwise looks good to me

**Comment by jbphet** [comment]
Corrected - my bad.  Closing.
