### ISSUE TITLE
Phase Diagram should be closed by default

### ISSUE THREAD

**Issue by arouinfar** [phetsims/states-of-matter-basics#6]
On the Phase Changes screen, the Phase Diagram panel should be minimized by default. This only applies to the basics version. 

![image](https://cloud.githubusercontent.com/assets/8419308/6451678/5760e5c8-c0ed-11e4-9da4-bb64fd98f35f.png)

**Comment by ChandrashekarBemagoni** [comment]
Fixed here https://github.com/phetsims/states-of-matter/commit/b69028b893f89ad903a4ec636b068b931c06e2c0. Assigning to @arouinfar  for verification

**Comment by arouinfar** [comment]
Fixed, closing.
