### ISSUE TITLE
is title correct?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter-basics#7]
Title is currently:
> "states-of-matter-basics.name": "States of Matter Basics"

Should it be "States of Matter: Basics"?  PhET's other "basics" sims have a colon before the "Basics".

**Comment by pixelzoom** [comment]
Other "basics" sims:

Circuit Construction Kit: Basics
Energy Skate Park: Basics
Forces and Motion: Basics
Molecules Shapes: Basics
pH Scale: Basics

**Comment by jbphet** [comment]
I added the colon, since that's how the title was for the Java version and, as @pixelzoom points out, it is more consistent with other sims.  Closing.
