### ISSUE TITLE
states-of-matter-basics fails to build

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/states-of-matter-basics#8]
```
% grunt 
…
Running "requirejs:build" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/Users/cmalley/PhET/GitHub/states-of-matter/js/atomic-interactions/view/GlobalOptionsNode.js'
>> In module tree:
>>     states-of-matter-basics-main
>> 
>>     at Object.fs.openSync (fs.js:427:18)
Warning: Task "requirejs:build" failed. Use --force to continue.

Aborted due to warnings.
%
```

**Comment by pixelzoom** [comment]
It's trying to get GlobalOptionsNode from atomic-interactions but that now lives in states-of-matter.  Probably something that was missed when atomic-interactions files were moved to states-of-matter.

**Comment by jbphet** [comment]
Yep, I missed this when moving the Atomic Interactions code into the states-of-matter repository.  Fixed now, and sim builds fine.  Closing.
